const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
class Sheet{constructor(){this.rows=[]}appendRow(r){this.rows.push([...r])}setFrozenRows(){}getLastRow(){return this.rows.length}getRange(r,c,n=1,w=1){return{getValues:()=>this.rows.slice(r-1,r-1+n).map(row=>row.slice(c-1,c-1+w)),setValue:v=>{this.rows[r-1][c-1]=v}}}}
const sheets={},ss={getSheetByName:n=>sheets[n]||null,insertSheet:n=>sheets[n]=new Sheet()};let live={};
const context={console,SpreadsheetApp:{getActiveSpreadsheet:()=>ss},PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'test-admin'})},Utilities:{DigestAlgorithm:{SHA_256:1},Charset:{UTF_8:1},computeDigest:(a,t)=>[...crypto.createHash('sha256').update(t).digest()],getUuid:()=>crypto.randomUUID()},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},CacheService:{getScriptCache:()=>({get:()=>null,put(){}})},UrlFetchApp:{fetch:u=>({getContentText:()=>JSON.stringify(u.endsWith('registry.json')?{gardens:[{garden_id:'PUBLIC-A',designer_id:'practice-a',garden_name:'Fixture public garden'}]}:live)})},safeStr:(v,n)=>String(v||'').trim().slice(0,n),jsonResp:v=>v,_neutralGardenSlug:g=>'g-'+crypto.createHash('sha256').update(g).digest('hex').slice(0,12)};
vm.createContext(context);let source=fs.readFileSync(__dirname+'/appsscript/Code.gs','utf8');vm.runInContext(source.slice(source.indexOf('/* Invited designer pilot.')),context);
const call=(action,data={})=>context.handleDesignerPortal({action,...data}),admin=(action,data={})=>call(action,{admin_token:'test-admin',...data});
assert.equal(call('create_practice',{name:'Unauthorised'}).ok,false);assert.equal(Object.keys(sheets).length,0);
const invite=id=>admin('create_practice',{designer_id:id,name:id,contact_email:id+'@example.invalid'}).access_link.split('#access=')[1];
const a=invite('practice-a'),b=invite('practice-b');assert.equal(a.length,64);assert.ok(!JSON.stringify(sheets).includes(a));
const garden={garden_name:'Fixture garden',suburb:'Fixture suburb',state:'VIC',garden_address:'PRIVATE FIXTURE ADDRESS',steward_email:'fixture@example.invalid',area_sqm:100,indigenous_species_current:12,structural_layers_current:3,canopy_cover_pct_current:15,habitat_nodes:2,consent_record:true,consent_public_profile:true,verification_level:'gardener_and_son_verified',designer_id:'practice-b',score:100};
const submit=(token,id,g= garden)=>call('submit_garden',{designer_token:token,request_id:id,garden:g});
assert.equal(submit(a,'bad-consent-00001',{...garden,consent_record:false}).ok,false);
assert.equal(submit(a,'bad-range-0000001',{...garden,canopy_cover_pct_current:101}).ok,false);
assert.equal(submit(a,'bad-count-0000001',{...garden,indigenous_species_current:1,species_list:'A\nB'}).ok,false);
const id=submit(a,'fixture-request-0001').submission_id;assert.ok(id);
assert.equal(submit(a,'fixture-request-0001').duplicate,true);assert.equal(sheets['Designer Submissions'].rows.length,2);
assert.equal(submit(b,'fixture-request-0001').ok,false);
const owned=call('get_submission',{designer_token:a,submission_id:id});assert.equal(owned.submission.payload.candidate.designer_id,'practice-a');assert.equal(owned.submission.payload.candidate.evidence.verification_level,'self_reported');assert.equal(owned.submission.payload.candidate.score,undefined);assert.equal(owned.submission.payload.candidate.garden_address,undefined);
assert.equal(call('get_submission',{designer_token:b,submission_id:id}).ok,false);
assert.equal(call('update_submission',{designer_token:b,submission_id:id,garden}).ok,false);
assert.equal(call('review_submission',{designer_token:a,submission_id:id,review_status:'ready'}).ok,false);
assert.equal(admin('export_submission',{submission_id:id}).ok,false);
assert.equal(admin('review_submission',{submission_id:id,review_status:'needs_changes',review_note:'Please check layers'}).ok,true);
assert.equal(call('update_submission',{designer_token:a,submission_id:id,garden}).ok,true);
const portfolio=call('get_portfolio',{designer_token:a});assert.equal(portfolio.gardens.length,1);assert.equal(portfolio.submissions.length,1);assert.ok(!JSON.stringify(portfolio).includes('PRIVATE FIXTURE ADDRESS'));assert.equal(call('get_portfolio',{designer_token:b}).submissions.length,0);
assert.equal(admin('review_submission',{submission_id:id,review_status:'ready'}).ok,true);
assert.equal(call('update_submission',{designer_token:a,submission_id:id,garden}).ok,false);
assert.equal(admin('export_submission',{submission_id:id}).ok,true);
assert.equal(admin('mark_published',{submission_id:id,garden_id:'ER-AU-VIC-FIXTURE'}).ok,false);
live={garden_id:'ER-AU-VIC-FIXTURE',designer_id:'practice-a'};assert.equal(admin('mark_published',{submission_id:id,garden_id:live.garden_id}).ok,true);assert.equal(admin('mark_published',{submission_id:id,garden_id:live.garden_id}).ok,true);assert.equal(sheets['Garden Addresses'].rows.length,2);assert.equal(sheets['Steward Emails'].rows.length,2);
assert.equal(admin('mark_published',{submission_id:id,garden_id:'ER-AU-VIC-OTHER'}).ok,false);
assert.equal(admin('review_submission',{submission_id:id,review_status:'ready'}).ok,false);
admin('rotate_practice_token',{designer_id:'practice-a'});assert.equal(call('get_portfolio',{designer_token:a}).ok,false);
admin('revoke_practice',{designer_id:'practice-b'});assert.equal(call('get_portfolio',{designer_token:b}).ok,false);
fs.writeFileSync('/tmp/designer-submission-fixture.json',JSON.stringify(owned.submission));
console.log('Designer portal: permissions, practice isolation, input validation, idempotency, review and private publication linkage passed.');
